Skip GetUID unit test on Windows
Windows does not have numeric user IDs like the POSIX OSes have.

--- FAIL: TestGetUID (0.01s)
    users_test.go:26: failed to find uid for root: No mapping between account names and security IDs was done.
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>