Fix Kine UNIX socket path URL handling
Kine UNIX socket paths used an authority, but aren't necessarily
absolute. Non-absolute paths (i.e. those that don't start with a slash)
cannot be encoded into URLs when using an authority. Fix this by
omitting the authority. Moreover, use the filepath package to make this
also work for Windows paths. NB: Absolute Windows paths will never start
with a slash, so the authority based encoding was almost always broken
there. Moreover, use url.URL to construct the URL string. This ensures
that the path gets properly encoded.

Add a test case for Kine etcd args and make related unit tests pass on
Windows, too.

This was the test failure on Windows:

 --- FAIL: TestApiServerSuite (0.01s)
    --- FAIL: TestApiServerSuite/TestGetEtcdArgs (0.00s)
        apiserver_test.go:56:
            	Error Trace:	D:\a\k0s\k0s\pkg\component\controller\apiserver_test.go:56
            	Error:      	"--etcd-cafile=\\var\\lib\\k0s\\pki\\etcd\\ca.crt" does not contain "--etcd-cafile=/var/lib/k0s/pki/etcd/ca.crt"
            	Test:       	TestApiServerSuite/TestGetEtcdArgs
        apiserver_test.go:57:
            	Error Trace:	D:\a\k0s\k0s\pkg\component\controller\apiserver_test.go:57
            	Error:      	"--etcd-certfile=\\var\\lib\\k0s\\pki\\apiserver-etcd-client.crt" does not contain "--etcd-certfile=/var/lib/k0s/pki/apiserver-etcd-client.crt"
            	Test:       	TestApiServerSuite/TestGetEtcdArgs
        apiserver_test.go:58:
            	Error Trace:	D:\a\k0s\k0s\pkg\component\controller\apiserver_test.go:58
            	Error:      	"--etcd-keyfile=\\var\\lib\\k0s\\pki\\apiserver-etcd-client.key" does not contain "--etcd-keyfile=/var/lib/k0s/pki/apiserver-etcd-client.key"
            	Test:       	TestApiServerSuite/TestGetEtcdArgs

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>