Fix version mismatch unit tests on Windows
The shell needs to be invoked explicitly on Windows. Moreover, the line
endings will be CRLF instead of just LF.

--- FAIL: TestConstants (0.02s)
    --- FAIL: TestConstants/KonnectivityImageVersion (0.01s)
        constant_shared_test.go:146:
            	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
            	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:37
            	Error:      	Received unexpected error:
            	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
            	Test:       	TestConstants/KonnectivityImageVersion
    --- FAIL: TestConstants/KubeProxyImageVersion (0.00s)
        constant_shared_test.go:146:
            	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
            	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:37
            	Error:      	Received unexpected error:
            	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
            	Test:       	TestConstants/KubeProxyImageVersion
    --- FAIL: TestConstants/KubernetesMajorMinorVersion (0.00s)
        constant_shared_test.go:146:
            	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
            	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:42
            	Error:      	Received unexpected error:
            	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
            	Test:       	TestConstants/KubernetesMajorMinorVersion
--- FAIL: TestKubernetesModuleVersions (0.00s)
    constant_shared_test.go:146:
        	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
        	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:50
        	Error:      	Received unexpected error:
        	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
        	Test:       	TestKubernetesModuleVersions
--- FAIL: TestEtcdModuleVersions (0.00s)
    constant_shared_test.go:146:
        	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
        	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:80
        	Error:      	Received unexpected error:
        	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
        	Test:       	TestEtcdModuleVersions
--- FAIL: TestContainerdModuleVersions (0.00s)
    constant_shared_test.go:146:
        	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
        	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:110
        	Error:      	Received unexpected error:
        	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
        	Test:       	TestContainerdModuleVersions
--- FAIL: TestRuncModuleVersions (0.00s)
    constant_shared_test.go:146:
        	Error Trace:	D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:146
        	            				D:\a\k0s\k0s\pkg\constant\constant_shared_test.go:126
        	Error:      	Received unexpected error:
        	            	fork/exec ./vars.sh: %1 is not a valid Win32 application.
        	Test:       	TestRuncModuleVersions
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>