Fix atomic file write tests on Windows
* Add special Windows expectations in cases where there's different
  behavior
* Skip tests that cannot be modeled on Windows

 --- FAIL: TestWriteAtomically (0.08s)
    --- FAIL: TestWriteAtomically/filePermissions (0.06s)
        --- FAIL: TestWriteAtomically/filePermissions/400 (0.02s)
            file_test.go:52:
                	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:52
                	Error:      	Not equal:
                	            	expected: 0x100
                	            	actual  : 0x124
                	Test:       	TestWriteAtomically/filePermissions/400
        --- FAIL: TestWriteAtomically/filePermissions/755 (0.01s)
            file_test.go:52:
                	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:52
                	Error:      	Not equal:
                	            	expected: 0x1ed
                	            	actual  : 0x1b6
                	Test:       	TestWriteAtomically/filePermissions/755
        --- FAIL: TestWriteAtomically/filePermissions/644 (0.01s)
            file_test.go:52:
                	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:52
                	Error:      	Not equal:
                	            	expected: 0x1a4
                	            	actual  : 0x1b6
                	Test:       	TestWriteAtomically/filePermissions/644
        --- FAIL: TestWriteAtomically/filePermissions/777 (0.01s)
            file_test.go:52:
                	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:52
                	Error:      	Not equal:
                	            	expected: 0x1ff
                	            	actual  : 0x1b6
                	Test:       	TestWriteAtomically/filePermissions/777
    --- FAIL: TestWriteAtomically/tempFileRemoved (0.00s)
        file_test.go:136:
            	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:136
            	            				D:\a\k0s\k0s\internal\pkg\file\file.go:115
            	            				D:\a\k0s\k0s\internal\pkg\file\file_test.go:131
            	Error:      	Received unexpected error:
            	            	remove C:\Users\RUNNER~1\AppData\Local\Temp\TestWriteAtomicallytempFileRemoved308452282\001\.file.324276745.tmp: The process cannot access the file because it is being used by another process.
            	Test:       	TestWriteAtomically/tempFileRemoved
    --- FAIL: TestWriteAtomically/pathObstructed (0.01s)
        file_test.go:173:
            	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:173
            	Error:      	Should be true
            	Test:       	TestWriteAtomically/pathObstructed
            	Messages:   	Expected fs.ErrExist: Access is denied.
    --- FAIL: TestWriteAtomically/tempPathObstructed (0.00s)
        file_test.go:201:
            	Error Trace:	D:\a\k0s\k0s\internal\pkg\file\file_test.go:201
            	            				D:\a\k0s\k0s\internal\pkg\file\file.go:115
            	            				D:\a\k0s\k0s\internal\pkg\file\file_test.go:194
            	Error:      	Received unexpected error:
            	            	remove C:\Users\RUNNER~1\AppData\Local\Temp\TestWriteAtomicallytempPathObstructed4278301068\001\.file.582359613.tmp: The process cannot access the file because it is being used by another process.
            	Test:       	TestWriteAtomically/tempPathObstructed
--- FAIL: TestExists (0.00s)
    file_test.go:271: test existing tempfile C:\Users\RUNNER~1\AppData\Local\Temp\TestExists1008844758\001\existing: got true, wanted false
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>