Fix SQLite URL path handling
SQLite paths used an authority, but aren't necessarily absolute.
Non-absolute paths (i.e. those that don't start with a slash) cannot be
encoded into URLs when using an authority. Fix this by omitting the
authority. Moreover, use the filepath package to make this also work for
Windows paths. NB: Absolute Windows paths will never start with a slash,
so the authority based encoding was almost always broken there.
Moreover, use url.URL to construct the URL string. This ensures that the
path gets properly encoded.

This was the test failure on Windows:

=== RUN   TestKinePartialConfigLoading
    storage_test.go:113:
                Error Trace:    C:\Users\twieczorek\Repos\k0s\pkg\apis\k0s.k0sproject.io\v1beta1\storage_test.go:113
                Error:          Not equal:
                                expected: "sqlite:///var/lib/k0s/db/state.db?mode=rwc&_journal=WAL&cache=shared"
                                actual  : "sqlite://C:\\var\\lib\\k0s/db/state.db?mode=rwc&_journal=WAL&cache=shared"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -sqlite:///var/lib/k0s/db/state.db?mode=rwc&_journal=WAL&cache=shared
                                +sqlite://C:\var\lib\k0s/db/state.db?mode=rwc&_journal=WAL&cache=shared
                Test:           TestKinePartialConfigLoading
--- FAIL: TestKinePartialConfigLoading (0.07s)
FAIL
FAIL    github.com/k0sproject/k0s/pkg/apis/k0s.k0sproject.io/v1beta1    0.699s
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>